
export interface Machine {
  type: 'Transplanter' | 'Ridging Machine';
  category: string;
  name: string;
  model: string;
  specs: Record<string, string>;
  features: string;
  imageUrls: string[];
  inferred?: boolean;
}

export const machines: Machine[] = [
  // Transplanters
  {
    type: 'Transplanter',
    category: 'Self-Propelled',
    name: 'Self-Propelled Transplanter',
    model: '2ZBZ-1 / 2ZBZ-2',
    specs: {
      'Total Weight': '400KG',
      'Overall Dimensions': '2650×1500×1760mm',
      'Working Rows': 'One or two rows',
      'Row Spacing': '300mm-500mm',
      'Plant Spacing': '200mm-400mm',
      'Power': '4.5KW gasoline or 6.5KW diesel engine',
      'Planting Depth': '50mm-100mm',
    },
    features: 'Ideal for small plots, hills, and greenhouses. It is a one-person operation and can automatically follow ridges.',
    imageUrls: [
      '/media/self_propelled_transplanter/18d8b11eef38c84dcc2a9013b428e7f7.mp4',
      '/media/self_propelled_transplanter/1b502f62252a043ddfd54d6302047f6f.mp4',
      '/media/self_propelled_transplanter/73d8780fb3b37887f175ae9548522704.mp4',
      '/media/self_propelled_transplanter/7bcb5422bdb33b6976f93ba25ab430bd.mp4',
      '/media/self_propelled_transplanter/de127e8346732d59be7e7a7aa1d73f32.mp4',
      '/media/self_propelled_transplanter/微信图片_20241225191128.jpg',
      '/media/self_propelled_transplanter/微信图片_20241225191156.jpg',
      '/media/self_propelled_transplanter/微信图片_20241225191212.jpg',
      '/media/self_propelled_transplanter/微信图片_20241225191220.jpg',
      '/media/self_propelled_transplanter/微信图片_20241225191228.jpg',
      '/media/self_propelled_transplanter/微信图片_20241225191236.jpg',
      '/media/self_propelled_transplanter/微信图片_20241225191247.jpg',
      '/media/self_propelled_transplanter/微信图片_20241225191254.jpg',
      '/media/self_propelled_transplanter/微信图片_20241225191303.jpg',
      '/media/self_propelled_transplanter/微信图片_20241225191311.jpg',
    ],
  },
  {
    type: 'Transplanter',
    category: 'Tractor-Pulled',
    name: 'Tractor-Pulled Two-Row Transplanter',
    model: '2ZBX-2 / 2ZBX-2A',
    specs: {
      'Total Weight': '500KG',
      'Overall Dimensions': '1850×1800×1500mm',
      'Working Rows': 'Two rows',
      'Row Spacing': '300mm-500mm',
      'Plant Spacing': '200mm-400mm',
      'Required Power': '≥40 horsepower',
      'Planting Depth': '50mm-100mm',
    },
    features: 'Widely used in vegetable, flower, and tobacco cultivation.',
    imageUrls: [
      '/media/two_row_transplanter/两行变速箱移栽机.mp4',
      '/media/two_row_transplanter/两行变速箱移栽机加施肥箱加覆膜功能.mp4',
      '/media/two_row_transplanter/两行变速箱移栽机加覆膜功能.mp4',
      '/media/two_row_transplanter/两行高配置变速箱移栽机.mp4',
      '/media/two_row_transplanter/两行高配置变速箱移栽机2.mp4',
      '/media/two_row_transplanter/两行高配置变速箱移栽机加覆膜功能.mp4',
      '/media/two_row_transplanter/变速箱两行移栽机1.jpg',
      '/media/two_row_transplanter/变速箱两行移栽机2.jpg',
      '/media/two_row_transplanter/变速箱两行移栽机3.jpg',
      '/media/two_row_transplanter/变速箱两行移栽机4.jpg',
      '/media/two_row_transplanter/变速箱两行移栽机高配1.jpg',
      '/media/two_row_transplanter/变速箱两行移栽机高配2.jpg',
      '/media/two_row_transplanter/变速箱两行移栽机高配3.jpg',
      '/media/two_row_transplanter/变速箱两行移栽机高配4.jpg',
      '/media/two_row_transplanter/变速箱两行移栽机高配5.jpg',
      '/media/two_row_transplanter/地轮传递两行移栽机1.jpg',
      '/media/two_row_transplanter/地轮传递两行移栽机2.jpg',
      '/media/two_row_transplanter/地轮传递两行移栽机3.jpg',
      '/media/two_row_transplanter/地轮传递两行移栽机4.jpg',
      '/media/two_row_transplanter/地轮传递两行移栽机5.jpg',
      '/media/two_row_transplanter/地轮传递两行移栽机6.jpg',
    ],
  },
  {
    type: 'Transplanter',
    category: 'Tractor-Pulled',
    name: 'Tractor-Pulled Three/Four-Row Transplanter',
    model: '2ZBX-3 / 2ZBX-4',
    specs: {
      'Total Weight': '800KG',
      'Overall Dimensions': '2450×2000×1600mm',
      'Working Rows': 'Three or four rows',
      'Row Spacing': '300mm-400mm',
      'Plant Spacing': '200mm-400mm',
      'Required Power': '≥70 horsepower',
      'Planting Depth': '50mm-100mm',
    },
    features: 'Ideal for large-scale vegetable, flower, and tobacco cultivation.',
    imageUrls: [
      '/media/three_four_row_transplanter/WeChat_20241227221932.mp4',
      '/media/three_four_row_transplanter/三行地轮传动移栽机.mp4',
      '/media/three_four_row_transplanter/三行地轮传动移栽机1.mp4',
      '/media/three_four_row_transplanter/四行移栽机.mp4',
      '/media/three_four_row_transplanter/四行移栽机1.mp4',
      '/media/three_four_row_transplanter/四行移栽机3.mp4',
      '/media/three_four_row_transplanter/四行移栽机带覆膜功能.mp4',
      '/media/three_four_row_transplanter/四行辣椒移栽机.mp4',
      '/media/three_four_row_transplanter/变速箱式四行移栽机.jpg',
      '/media/three_four_row_transplanter/变速箱式四行移栽机2.jpg',
      '/media/three_four_row_transplanter/变速箱式四行移栽机3.jpg',
      '/media/three_four_row_transplanter/变速箱移栽机三行带覆膜功能1.jpg',
      '/media/three_four_row_transplanter/变速箱移栽机三行带覆膜功能2.jpg',
      '/media/three_four_row_transplanter/变速箱移栽机三行带覆膜功能3.jpg',
      '/media/three_four_row_transplanter/地轮传动四行移栽机.jpg',
      '/media/three_four_row_transplanter/地轮传动四行移栽机2.jpg',
      '/media/three_four_row_transplanter/地轮传动四行移栽机3.jpg',
      '/media/three_four_row_transplanter/地轮传动四行移栽机4.jpg',
      '/media/three_four_row_transplanter/地轮传动四行移栽机5.jpg',
    ],
  },
  {
    type: 'Transplanter',
    category: 'Specialized',
    name: 'Pineapple Transplanter',
    model: '2ZBX-2P',
    specs: {
      'Required Power': '≥90 horsepower',
      'Working Rows': 'Two or four rows',
    },
    features: 'Specialized for planting pineapples, can also be used for other crops. Can perform ridging, mulching, planting, and fertilizing all in one go.',
    imageUrls: [
      '/media/pineapple_transplanter/WeChat_20241230191616.mp4',
      '/media/pineapple_transplanter/WeChat_20241230191645.mp4',
      '/media/pineapple_transplanter/WeChat_20241230191650.mp4',
      '/media/pineapple_transplanter/WeChat_20241230191654.mp4',
      '/media/pineapple_transplanter/两行菠萝起垄覆膜移栽机一体机.jpg',
      '/media/pineapple_transplanter/两行菠萝起垄覆膜移栽机一体机1.jpg',
      '/media/pineapple_transplanter/两行菠萝起垄覆膜移栽机一体机2.jpg',
      '/media/pineapple_transplanter/两行菠萝起垄覆膜移栽机一体机3.jpg',
      '/media/pineapple_transplanter/两行菠萝起垄覆膜移栽机一体机4.jpg',
      '/media/pineapple_transplanter/两行菠萝起垄覆膜移栽机一体机5.jpg',
      '/media/pineapple_transplanter/两行菠萝起垄覆膜移栽机一体机6.jpg',
      '/media/pineapple_transplanter/两行菠萝起垄覆膜移栽机一体机带苗框.jpg',
      '/media/pineapple_transplanter/两行菠萝起垄覆膜移栽机一体机带苗框1.jpg',
      '/media/pineapple_transplanter/两行菠萝起垄覆膜移栽机一体机带苗框2.jpg',
      '/media/pineapple_transplanter/两行菠萝起垄覆膜移栽机一体机带苗框3.jpg',
      '/media/pineapple_transplanter/菠萝四行起垄覆膜移栽施肥一体机1.jpg',
      '/media/pineapple_transplanter/菠萝四行起垄覆膜移栽施肥一体机2.jpg',
      '/media/pineapple_transplanter/菠萝四行起垄覆膜移栽施肥一体机3.jpg',
      '/media/pineapple_transplanter/菠萝四行起垄覆膜移栽施肥一体机4.jpg',
      '/media/pineapple_transplanter/菠萝四行起垄覆膜移栽施肥一体机5.jpg',
    ],
    inferred: true
  },
  // Ridging Machines
  {
    type: 'Ridging Machine',
    category: 'Single Ridge',
    name: 'Single Ridge Machine',
    model: 'Single Ridge Ridger',
    specs: {},
    features: 'Basic ridging function for a single row. Perfect for creating ideal soil conditions for root vegetables like carrots, or for general use in smaller scale operations.',
    imageUrls: [
      '/media/ridging_machine/单垄起垄机.mp4',
      '/media/ridging_machine/单垄起垄机.jpg',
      '/media/ridging_machine/单垄起垄机1.jpg',
      '/media/ridging_machine/单垄起垄机2.jpg',
      '/media/ridging_machine/单垄起垄机3.jpg',
    ],
    inferred: true
  },
  {
    type: 'Ridging Machine',
    category: 'Double Ridge',
    name: 'Double Ridge Machine',
    model: 'Double Ridge Ridger',
    specs: {},
    features: 'Efficiently creates two ridges simultaneously. Excellent for preparing fields for crops like carrots that benefit from well-defined ridges.',
    imageUrls: [
      '/media/ridging_machine/双垄起垄机.mp4',
      '/media/ridging_machine/双垄起垄机2.mp4',
      '/media/ridging_machine/双龙起垄.jpg',
      '/media/ridging_machine/WeChat_20250103203219.mp4',
    ],
    inferred: true
  },
  {
    type: 'Ridging Machine',
    category: 'Double Ridge with Mulching',
    name: 'Double Ridge Machine with Mulching',
    model: 'Double Ridge Ridger + Mulch',
    specs: {},
    features: 'Creates two ridges and applies a layer of plastic film (mulch) at the same time. Ideal for weed control and moisture retention in double-row planting.',
    imageUrls: [
      '/media/ridging_machine/双垄起垄机带覆膜功能.mp4',
      '/media/ridging_machine/双垄起垄机带覆膜功能1.mp4',
      '/media/ridging_machine/双垄起垄机带覆膜功能2.mp4',
      '/media/ridging_machine/双垄覆膜一体机.jpg',
      '/media/ridging_machine/双垄起垄覆膜机.mp4',
      '/media/ridging_machine/双垄起垄覆膜机.1mp4.jpg',
      '/media/ridging_machine/双垄起垄覆膜机一体机.jpg',
    ],
    inferred: true
  },
  {
    type: 'Ridging Machine',
    category: 'All-in-One',
    name: 'Vegetable Ridging, Mulching, and Seeding Machine',
    model: 'Vegetable Ridger + Mulch + Seeder',
    specs: {},
    features: 'An all-in-one machine for vegetable planting. Creates ridges, applies mulch, and plants seeds.',
    imageUrls: ['/media/ridging_machine/蔬菜起垄覆膜播种一体机.mp4'],
    inferred: true
  },
  {
    type: 'Ridging Machine',
    category: 'Specialized',
    name: 'Onion Mulching and Hole Punching Machine',
    model: 'Onion Mulch + Hole Punch',
    specs: {},
    features: 'A specialized machine for planting onions. Applies mulch and punches holes for planting.',
    imageUrls: [
      '/media/ridging_machine/洋葱覆膜打孔一体机.mp4',
      '/media/ridging_machine/洋葱起垄覆膜机打孔一体机.mp4',
      '/media/ridging_machine/洋葱起垄覆膜机打孔一体机1.mp4',
    ],
    inferred: true
  },
  {
    type: 'Ridging Machine',
    category: 'Specialized',
    name: 'Carrot Ridging Machine',
    model: 'Carrot Ridger',
    specs: {},
    features: 'Specialized machine for creating ridges for carrots.',
    imageUrls: ['/media/ridging_machine/胡萝卜起垄.mp4'],
    inferred: true
  },
  {
    type: 'Ridging Machine',
    category: 'Specialized',
    name: 'Seedbed Ridging Machine',
    model: 'Seedbed Ridger',
    specs: {},
    features: 'Machine for creating seedbeds.',
    imageUrls: ['/media/ridging_machine/苗床起垄机.mp4'],
    inferred: true
  }
];
